services:
  postgres:
      image: postgres:16-alpine
      env_file:
        - .env
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data
      networks:
        - app-network

  users-service:
      build: ./users_service
      ports:
        - "${USERS_SERVICE_PORT}:8000"
      env_file:
        - .env
      depends_on:
        - postgres
      networks:
        - app-network

  product-service:
      build: ./products_service
      ports:
        - "${PRODUCTS_SERVICE_PORT}:8000"
      env_file:
        - .env
      depends_on:
        - postgres
      networks:
        - app-network

  orders-service:
      build: ./orders_service
      ports:
        - "${ORDERS_SERVICE_PORT}:8000"
      env_file:
        - .env
      depends_on:
        - postgres
        - product-service
        - users-service
      networks:
        - app-network

volumes:
  pgdata:


networks:
  app-network:
    driver: bridge
