services:
  postgres:
      image: postgres:16-alpine
      env_file:
        - .env
      ports:
        - "5432:5432"
      volumes:
        - 184e8592ccb7367406c41adf35489b7253c95e18bd621195b9f97323cccc16b3:/var/lib/postgresql/data
      networks:
        - app-network

  users-service:
      build: ./users_service
      ports:
        - "8001:8000"
      env_file:
        - .env
      depends_on:
        - postgres
      networks:
        - app-network

volumes:
  184e8592ccb7367406c41adf35489b7253c95e18bd621195b9f97323cccc16b3:
    external: true

networks:
  app-network:
    driver: bridge
